services:
  evrinoma.gallery.constraint.property.gallery.title:
    class: Evrinoma\GalleryBundle\Constraint\Property\Gallery\Title

  evrinoma.gallery.constraint.property.gallery.preview:
    class: Evrinoma\GalleryBundle\Constraint\Property\Gallery\Preview

  evrinoma.gallery.constraint.property.gallery.active:
    class: Evrinoma\GalleryBundle\Constraint\Property\Gallery\Active

  evrinoma.gallery.constraint.property.gallery.position:
    class: Evrinoma\GalleryBundle\Constraint\Property\Gallery\Position


